### ISSUE TITLE
Convert audio files before passing them to pydub

### ISSUE THREAD

**Issue by tinok** [dighr/audio_analysis#24]
Some audio files are not encoded in a way that `pydub` is able to process them, resulting in errors. 

One solution would be to just always use ffmpeg -i oldfile newfile to convert files before passing them to pydub. 

This library may help: https://github.com/kkroening/ffmpeg-python

**Comment by tinok** [comment]
@mdrafiurYU Can this be closed? I think this has been addressed.

**Comment by mdrafiurYU** [comment]
Yes, addressed and closing.
