### ISSUE TITLE
Sign in page

### ISSUE THREAD

**Issue by tinok** [dighr/audio_analysis#28]
![image](https://user-images.githubusercontent.com/673511/69755269-dac49580-1125-11ea-83ac-73cff9f7e7fc.png)

Use the standard Django user sign in view. For now, users need to be created on the backend (no registration view needed).

**Comment by mdrafiurYU** [comment]
Sign in page created - can be accessed at https://nlp.openendeddata.org/accounts/login/

**Comment by mdrafiurYU** [comment]
Currently, 'admin' user is created with 
Username: admin
Password: dighr2020

Attempt to log in with incorrect credential displays an error message and upon successful login redirects to the home page.
